window.memberCards = [
  {
    letter: 'A',
    initials: 'AL',
    name: 'Ada Lin',
    avatar: 'avatars/ruby.png',
    previewRole: 'System Design',
    slogan: 'Build systems that stay calm under pressure.',
    detailRole: 'System Design Lead',
    description: 'Owns platform structure, standards, and interface consistency across the institute.',
    website: 'https://sti.team/ada',
    websiteLabel: 'sti.team/ada',
    tx: '-22px',
    ty: '14px',
    rot: '-8deg',
    z: 110,
  },
  {
    letter: 'B',
    initials: 'NK',
    name: 'Noah Kim',
    avatar: 'avatars/blake.png',
    previewRole: 'Frontend Engineering',
    slogan: 'Ship interfaces that feel fast and obvious.',
    detailRole: 'Frontend Engineering Lead',
    description: 'Maintains component quality, performance budgets, and accessibility baselines.',
    website: 'https://sti.team/noah',
    websiteLabel: 'sti.team/noah',
    tx: '-16px',
    ty: '10px',
    rot: '-6deg',
    z: 100,
  },
  {
    letter: 'C',
    initials: 'IC',
    name: 'Iris Chen',
    avatar: 'avatars/wiess.png',
    previewRole: 'Interaction Motion',
    slogan: 'Motion should explain, not decorate.',
    detailRole: 'Interaction Motion Director',
    description: 'Designs spatial transitions and micro timing for navigation cues and handoffs.',
    website: 'https://sti.team/iris',
    websiteLabel: 'sti.team/iris',
    tx: '-10px',
    ty: '6px',
    rot: '-4deg',
    z: 90,
  },
  {
    letter: 'D',
    initials: 'LP',
    name: 'Luca Park',
    avatar: 'avatars/yang.png',
    previewRole: 'Visual Direction',
    slogan: 'Contrast creates direction at a glance.',
    detailRole: 'Visual Direction Lead',
    description: 'Directs type, contrast, and composition across all digital and printed touchpoints.',
    website: 'https://sti.team/luca',
    websiteLabel: 'sti.team/luca',
    tx: '-4px',
    ty: '2px',
    rot: '-2deg',
    z: 80,
  },
  {
    letter: 'E',
    initials: 'EY',
    name: 'Erina Yip',
    avatar: 'avatars/E.png',
    previewRole: 'Frontend Development, Cybersecurity',
    slogan: 'That you are here, that life exists and identity, That the powerful play goes on, and you may contribute a verse.',
    detailRole: 'Frontend Development, Cybersecurity',
    description: 'Builds resilient interfaces and explores secure implementation details across the web stack.',
    website: 'https://blog.erina.top',
    websiteLabel: 'blog.erina.top',
    tx: '2px',
    ty: '-2px',
    rot: '0deg',
    z: 70,
  },
  {
    letter: 'F',
    initials: 'EW',
    name: 'Eli Wang',
    avatar: 'avatars/blake.png',
    previewRole: 'Design Ops',
    slogan: 'Good systems make delivery feel inevitable.',
    detailRole: 'Design Ops Manager',
    description: 'Coordinates delivery systems, versioning, and design governance for the team.',
    website: 'https://sti.team/eli',
    websiteLabel: 'sti.team/eli',
    tx: '8px',
    ty: '-6px',
    rot: '2deg',
    z: 60,
  },
  {
    letter: 'G',
    initials: 'SH',
    name: 'Sora Han',
    avatar: 'avatars/wiess.png',
    previewRole: 'UX Research',
    slogan: 'Listen closely before changing the map.',
    detailRole: 'UX Research Lead',
    description: 'Validates information architecture through interviews, observation, and testing loops.',
    website: 'https://sti.team/sora',
    websiteLabel: 'sti.team/sora',
    tx: '14px',
    ty: '-10px',
    rot: '4deg',
    z: 50,
  },
  {
    letter: 'H',
    initials: 'YQ',
    name: 'Yuna Qiu',
    avatar: 'avatars/yang.png',
    previewRole: 'Content Strategy',
    slogan: 'Sharp language gives structure a voice.',
    detailRole: 'Content Strategy Lead',
    description: 'Crafts concise messaging systems and editorial hierarchy for every surface.',
    website: 'https://sti.team/yuna',
    websiteLabel: 'sti.team/yuna',
    tx: '20px',
    ty: '-14px',
    rot: '6deg',
    z: 40,
  },
  {
    letter: 'I',
    initials: 'KI',
    name: 'Ken Ito',
    avatar: 'avatars/ruby.png',
    previewRole: 'Product Strategy',
    slogan: 'Priorities matter only when they are measurable.',
    detailRole: 'Product Strategy Partner',
    description: 'Aligns roadmap priorities with measurable outcomes and execution tradeoffs.',
    website: 'https://sti.team/ken',
    websiteLabel: 'sti.team/ken',
    tx: '26px',
    ty: '-18px',
    rot: '8deg',
    z: 30,
  },
  {
    letter: 'J',
    initials: 'NL',
    name: 'Nia Luo',
    avatar: 'avatars/blake.png',
    previewRole: 'Prototyping',
    slogan: 'Prototype the question before the answer.',
    detailRole: 'Rapid Prototyping Specialist',
    description: 'Builds fast, high-fidelity prototypes for product validation and team alignment.',
    website: 'https://sti.team/nia',
    websiteLabel: 'sti.team/nia',
    tx: '32px',
    ty: '-22px',
    rot: '10deg',
    z: 20,
  },
];
